server {
  listen 80;
  server_name _;

  root /var/www/html;
  index index.php index.html;
  charset utf-8;

  client_max_body_size 32m;

  location / {
    if (!-e $request_filename) {
      rewrite ^/(.[a-zA-Z0-9\-_]+).html$ /index.php?mod=$1 last;
    }
    rewrite ^/pay/(.*)$ /pay.php?s=$1 last;
    rewrite ^/api/(.*)$ /api.php?s=$1 last;
    rewrite ^/doc/(.[a-zA-Z0-9\-_]+).html$ /index.php?doc=$1 last;
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ^~ /plugins {
    deny all;
  }

  location ^~ /includes {
    deny all;
  }

  location ^~ /install {
    deny all;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
    fastcgi_pass php:9000;
    fastcgi_index index.php;
  }

  location ~* \.(css|js|jpg|jpeg|gif|png|svg|ico|webp|woff|woff2)$ {
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
    try_files $uri =404;
  }
}
